version: "3.3"

networks:
  net:
    driver: overlay
    attachable: true

volumes:
    prometheus: {}
    grafana: {}
    alertmanager: {}

services:
  cadvisor:
    image: google/cadvisor
    ports:
      - "8080:8080"
    networks:
      - net
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana:
    image: ale8193/grafana
    ports:
      - "3000:3000"
    networks:
      - net
    env_file:
      - ./grafana/.env
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana:/var/lib/grafana
#      - ./grafana/dashboards:/etc/grafana/dashboards
#      - ./grafana/datasources:/etc/grafana/provisioning/datasources
#      - ./grafana/swarmprom_dashboards.yml:/etc/grafana/provisioning/dashboards/swarmprom_dashboards.yml
    deploy:
      mode: replicated
      replicas: 3
      #placement:
      #  constraints:
      #    - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  alertmanager:
    image: ale8193/alertmanager
    ports:
      - "9093:9093"
    networks:
      - net
    command:
      - '--config.file=/etc/alertmanager/conf/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
#      - ./alertmanager/conf:/etc/alertmanager/conf
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  smtp:
    image: namshi/smtp
    ports:
     - "25:25"
    networks:
      - net
    environment:
     #  # MUST start with : e.g RELAY_NETWORKS: :192.168.0.0/24:10.0.0.0/16
     #  # if acting as a relay this or RELAY_DOMAINS must be filled out or incoming mail will be rejected
     #  RELAY_NETWORKS: :192.168.0.0/24
     #  # what domains should be accepted to forward to lower distance MX server.
     #  RELAY_DOMAINS: <domain1> : <domain2> : <domain3>
     #  # To act as a Gmail relay
     #  GMAIL_USER:
     #  GMAIL_PASSWORD:
     #  # For use with Amazon SES relay
     #  SES_USER:
     #  SES_PASSWORD:
     #  SES_REGION:
     #  # if provided will enable TLS support
     #  KEY_PATH:
     #  CERTIFICATE_PATH:
     #  # the outgoing mail hostname
      MAILNAME: alert.imolab.it
     #  # set this to any value to disable ipv6
     #  DISABLE_IPV6:
     # # Generic SMTP Relay
     # SMARTHOST_ADDRESS:
     # SMARTHOST_PORT:
     # SMARTHOST_USER:
     # SMARTHOST_PASSWORD:
     # SMARTHOST_ALIASES:
    deploy:
      mode: replicated
      replicas: 3
      #placement:
      #  constraints:
      #    - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  node-exporter:
    image: ale8193/node-exporter
    networks:
      - net
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    image: ale8193/prometheus
    ports:
     - "9090:9090"
    networks:
      - net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=24h'
    volumes:
      - prometheus:/prometheus
#      - ./prometheus/conf:/etc/prometheus
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
