apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
- name: Prometheus
  type: prometheus
  access: direct
  url: http://pippo.imolab.it:9090
  isDefault: true
  version: 1
  editable: true
